export const siteConfig = {
	name: "coupon-generator",
	url: "https://coupon-generator.colidevs.com",
	ogImage: "https://coupon-generator.colidevs.com/og.jpg",
	description: "coupon-generator generated by create-coliapp",
	links: {
		instagram: "https://instagram.com/colidevs",
	},
};

export type SiteConfig = typeof siteConfig;
